service: myserverlessproject2

provider:
    name: aws
    runtime: nodejs12.x
    profile: serverlessUser
    region: eu-west-1
    iamRoleStatements:
        - Effect: Allow
          Action:
              - comprehend:*
          Resource: '*'

functions:
    analyse:
        handler: lambdas/endpoints/analyse.handler
        events:
            - http:
                  path: analyse
                  method: POST
                  cors: true
