service: myserverlessproject3

provider:
    name: aws
    runtime: nodejs12.x
    profile: serverlessUser
    region: eu-west-1
    stage: dev
    environment:
        tableName: ${self:custom.tableName}
        bucketName: ${self:custom.bucketName}
        tokenTableName: ${self:custom.tokenTableName}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
              - s3:*
              - ses:*
          Resource: '*'

plugins:
    - serverless-webpack

package:
    individually: true

custom:
    tableName: player-points-table
    tokenTableName: token-table-name
    bucketName: myserverlessprojectuploadbucket-12312356

functions:
    authoriserAnyToken:
        handler: lambdas/authorisers/anyToken.handler

    getPlayerScore:
        handler: lambdas/endpoints/getPlayerScore.handler
        events:
            - http:
                  path: get-player-score/{ID}
                  method: GET
                  cors: true
                  authorizer:
                      name: authoriserAnyToken
                      type: request
                      identitySource: method.request.header.X-Amz-Security-Token
    createPlayerScore:
        handler: lambdas/endpoints/createPlayerScore.handler
        events:
            - http:
                  path: create-player-score/{ID}
                  method: POST
                  cors: true
                  authorizer:
                      name: authoriserAnyToken
                      type: request
                      identitySource: method.request.header.X-Amz-Security-Token
    updatePlayerScore:
        handler: lambdas/endpoints/updatePlayerScore.handler
        events:
            - http:
                  path: update-player-score/{ID}
                  method: PUT
                  cors: true
    getGameScores:
        handler: lambdas/endpoints/getGameScores.handler
        events:
            - http:
                  path: get-game-scores/{game}
                  method: GET
                  cors: true

    getGamesForPlayer:
        handler: lambdas/endpoints/getGamesForPlayer.handler
        events:
            - http:
                  path: get-games-for-player/{playerID}
                  method: GET
                  cors: true

    sendEmail:
        handler: lambdas/endpoints/sendEmail.handler
        events:
            - http:
                  path: send-email
                  method: POST
                  cors: true

resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:custom.bucketName}
        MyDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                    - AttributeName: game
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST

                GlobalSecondaryIndexes:
                    - IndexName: game-index
                      KeySchema:
                          - AttributeName: game
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL

        TokenTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tokenTableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S

                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
